version: "3"

services:
  web:
    build: .
    ports:
      - "3000:3000"

    volumes:
      - .:/usr/src/ruby-bank
    env_file:
      - .env/development/database
      - .env/development/web
      - .env/test/database
      - .env/test/web

  database:
     image: postgres
     env_file:
      - .env/development/database
      - .env/test/database
